import type { ApplyShopFixtureAutoFixesInput, ApplyShopFixtureAutoFixesResult, AnalyzeShopFixturesInput, AnalyzeShopFixturesResult, ExportArtifactsInput, ExportArtifactsResult, TimelineFindingsExportBundle, TimelineFindingsExportBundleInput, ImportShopFixtureInput, ImportShopFixtureResult, PreviewShopFixtureAutoFixesInput, PreviewShopFixtureAutoFixesResult, RestoreShopFixtureManifestBackupInput, RestoreShopFixtureManifestBackupResult, RunShopRegressionTestsInput, RunShopRegressionTestsResult, ValidateShopFixturesInput, ValidateShopFixturesResult, FormatStyle, LintIssue, ParameterReserveProfile, ParameterizeOptions, ParameterizeResult, ProgramTemplate, ProgramAdvisorOptions, ProgramAdvisorReport, ProgramAst, RunJobCheckInput, RunJobCheckResult, ProveoutPatchResult, ProveoutResult, SetupSheet, SimulationResult, SimulatorLimits, TemplateLibrary, ToolingReport, ToolingReportOptions } from "./types.js";
export type ControllerProfile = {
    id: string;
    name: string;
    defaultFormatStyle: FormatStyle;
    validateAst?: (ast: ProgramAst) => LintIssue[];
};
export declare function parse(code: string, profile: ControllerProfile): ProgramAst;
export declare function format(ast: ProgramAst, profile: ControllerProfile, style?: Partial<FormatStyle>): string;
export declare function parameterize(ast: ProgramAst, options?: ParameterizeOptions): ParameterizeResult;
export declare function simulate(ast: ProgramAst, initialState: Record<string, number>, limits: SimulatorLimits): SimulationResult;
export declare function lint(ast: ProgramAst, profile: ControllerProfile): LintIssue[];
export declare function toolingReport(ast: ProgramAst, initialState: Record<string, number>, options?: ToolingReportOptions): ToolingReport;
export declare function analyzeProgram(ast: ProgramAst, initialState: Record<string, number>, options?: ProgramAdvisorOptions): ProgramAdvisorReport;
export declare function getProgramTemplates(): ProgramTemplate[];
export declare function getTemplateLibrary(): TemplateLibrary;
export declare function parseTemplateLibrary(sourceJson: string): TemplateLibrary;
export declare function parameterReserveProfiles(): ParameterReserveProfile[];
export declare function buildSetupSheet(ast: ProgramAst, initialState: Record<string, number>): SetupSheet;
export declare function proveoutProgram(ast: ProgramAst, initialState: Record<string, number>): ProveoutResult;
export declare function applyProveout(code: string, markerLines: string[]): ProveoutPatchResult;
export declare function removeProveout(code: string): ProveoutPatchResult;
export declare function exportWorkshopFiles(input: ExportArtifactsInput): Promise<ExportArtifactsResult>;
export declare function buildTimelineFindingsExportBundle(input: TimelineFindingsExportBundleInput): TimelineFindingsExportBundle;
export declare function runJobCheck(input: RunJobCheckInput): Promise<RunJobCheckResult>;
export declare function importShopFixture(input: ImportShopFixtureInput): Promise<ImportShopFixtureResult>;
export declare function validateShopFixturesManifest(input: ValidateShopFixturesInput): Promise<ValidateShopFixturesResult>;
export declare function runShopRegressionTests(input: RunShopRegressionTestsInput): Promise<RunShopRegressionTestsResult>;
export declare function analyzeShopFixtureHealth(input: AnalyzeShopFixturesInput): Promise<AnalyzeShopFixturesResult>;
export declare function previewShopFixtureAutoFixes(input: PreviewShopFixtureAutoFixesInput): Promise<PreviewShopFixtureAutoFixesResult>;
export declare function applyShopFixtureAutoFixes(input: ApplyShopFixtureAutoFixesInput): Promise<ApplyShopFixtureAutoFixesResult>;
export declare function restoreShopFixtureManifestBackup(input: RestoreShopFixtureManifestBackupInput): Promise<RestoreShopFixtureManifestBackupResult>;
